"use server"

import { createClient } from "@/lib/supabase/server"
import { redirect } from "next/navigation"

export async function signUp(formData: FormData) {
  const supabase = await createClient()

  const username = (formData.get("username") as string)?.trim().toLowerCase()
  const email    = (formData.get("email")    as string)?.trim().toLowerCase()
  const password = (formData.get("password") as string)

  if (!username || username.length < 3)
    return { error: "Username must be at least 3 characters" }

  if (!/^[a-z0-9_]+$/.test(username))
    return { error: "Username may only contain letters, numbers, and underscores" }

  if (!password || password.length < 8)
    return { error: "Password must be at least 8 characters" }

  // Check username taken BEFORE creating auth user
  const { data: existing } = await supabase
    .from("profiles")
    .select("id")
    .eq("username", username)
    .single()

  if (existing) return { error: "Username is already taken" }

  // Use real email if provided, else generate internal one
  const authEmail = email || `${username}@jobsync.internal`

  const { data, error: signUpError } = await supabase.auth.signUp({
    email:    authEmail,
    password,
    options: { data: { username } },
  })

  if (signUpError) return { error: signUpError.message }
  if (!data.user)  return { error: "Signup failed — please try again" }

  // Insert profile (friend_code auto-generated by DB trigger)
  const { error: profileError } = await supabase
    .from("profiles")
    .insert({ id: data.user.id, username } as never)

  if (profileError) return { error: "Failed to create profile: " + profileError.message }

  redirect("/dashboard")
}

export async function signIn(formData: FormData) {
  const supabase = await createClient()

  const username = (formData.get("username") as string)?.trim().toLowerCase()
  const password = (formData.get("password") as string)

  if (!username) return { error: "Please enter your username" }
  if (!password) return { error: "Please enter your password" }

  // Supabase auth needs email — map username → internal email
  const authEmail = username.includes("@") ? username : `${username}@jobsync.internal`

  const { error } = await supabase.auth.signInWithPassword({
    email: authEmail,
    password,
  })

  if (error) {
    if (error.message.includes("Invalid login")) return { error: "Incorrect username or password" }
    if (error.message.includes("Email not confirmed")) return { error: "Account not confirmed — check your email" }
    return { error: error.message }
  }

  redirect("/dashboard")
}

export async function signOut() {
  const supabase = await createClient()
  await supabase.auth.signOut()
  redirect("/login")
}

export async function getCurrentUser() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return null

  const { data: profile } = await supabase
    .from("profiles")
    .select("*")
    .eq("id", user.id)
    .single()

  return { user, profile }
}
